package com.froi.graficador.lexer;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 6;
  public static final int UNARY = 21;
  public static final int CURVA = 14;
  public static final int ANIMAR = 11;
  public static final int COLOR = 20;
  public static final int COM = 10;
  public static final int SIGMENOS = 17;
  public static final int CUADRADO = 4;
  public static final int PARC = 9;
  public static final int OBJETO = 12;
  public static final int SIGDIVISION = 19;
  public static final int PARA = 8;
  public static final int GRAFICAR = 2;
  public static final int SIGSUMA = 16;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NUMERO = 15;
  public static final int POLIGONO = 7;
  public static final int CIRCULO = 3;
  public static final int SIGMULTIPLICACION = 18;
  public static final int ANTERIOR = 13;
  public static final int RECTANGULO = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GRAFICAR",
  "CIRCULO",
  "CUADRADO",
  "RECTANGULO",
  "LINEA",
  "POLIGONO",
  "PARA",
  "PARC",
  "COM",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "CURVA",
  "NUMERO",
  "SIGSUMA",
  "SIGMENOS",
  "SIGMULTIPLICACION",
  "SIGDIVISION",
  "COLOR",
  "UNARY"
  };
}

